[general]
live_config_reload = true

[window]
opacity = 0.9
# blur = true

[scrolling]
history = 100000

[mouse]
hide_when_typing = true

[font]
size = 8

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Heavy"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Heavy Italic"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Medium Italic"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[terminal]
osc52 = "CopyPaste"

[keyboard]
bindings = [
        { key = "M", mods = "Control|Shift", action = "ToggleMaximized" },
        { key = "Q", mods = "Control|Shift", action = "Quit" },
        { key = "N", mods = "Control|Shift", action = "SpawnNewInstance" },
]


# Colors (Gruvbox dark)

# Default colors
[colors.primary]
# hard contrast background = = '#1d2021'
background = '#282828'
# soft contrast background = = '#32302f'
foreground = '#ebdbb2'

# Normal colors
[colors.normal]
black   = '#282828'
red     = '#cc241d'
green   = '#98971a'
yellow  = '#d79921'
blue    = '#458588'
magenta = '#b16286'
cyan    = '#689d6a'
white   = '#a89984'

# Bright colors
[colors.bright]
black   = '#928374'
red     = '#fb4934'
green   = '#b8bb26'
yellow  = '#fabd2f'
blue    = '#83a598'
magenta = '#d3869b'
cyan    = '#8ec07c'
white   = '#ebdbb2'
