add_newline = false
format = "$directory$character"
right_format = "$all"

[hostname]
disabled = true

[cmd_duration]
disabled = true

[username]
disabled = true

[time]
disabled = false
format = "[$time]($style)"
utc_time_offset = "-7" #los angeles
