# ~/.config/starship.toml

# A minimal left prompt
format = """$directory$character"""

# move the rest of the prompt to the right
right_format = """$all"""

add_newline = false

[hostname]
disabled = false
format = '[$ssh_symbol]($style) '

[cmd_duration]
disabled = true

[username]
disabled = true

[time]
disabled = false
format = '[$time]($style)'
utc_time_offset = '-7'

[character]
success_symbol = '[❯](bold green) '
error_symbol = '[✗](bold red) '

